---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Unifynd Interview Assessment: Data Analytics

<!-- badges: start -->
<!-- badges: end -->

The goal of the *Unifynd Interview Assessment: Data Analytics* task is to use 3 data sources (customerUser, customerScans, couponTransaction) to answer 8 data analysis questions. The questions can be found in the introductory PDF (InterviewAssignmentDataAnalytics.pdf) file in the root of the directory.


## File Structure 

* To ensure that best practices are followed  (by design), this entire task is executed as a R package. 

* This is why I have shared the entire package directory with you as my submission for this data task.

* In the directory above, there is a .RProj (R project file). If you open it in R Studio (R Studio is required for running this), you will have all the relevant environment needed for you to run this R Markdown Notebook (named: unifyndInterviewAssessmentRNotebook.Rmd). Note that this file has a .Rmd extension.

* This R notebook contains all the code, output and answers for all of the 7 questions(and its sub-parts) in the task. This R Notebook (.Rmd file) is present in the root of the package directory. 

* Also all the helper (.R) scripts, other than this .Rmd file, can be found in the **R** sub-directory.

* Just make sure that you have all the R packages (mentioned in the "load_libraries" chunk in this R Notebook below) installed on your system.

* Also, make sure that your paths are set as per your system. I have used relative paths in the code, but still it is good to have this as a Sanity check before running the code.

* Once you have followed all of the above steps, please continue reading below on how to use this R Notebook.

## How to use the R Markdown notebook?

* You can preview this notebook using the **Preview** button, which will show you a rendered HTML copy of the contents of the editor. 

* The other option is to knit this notebook into a neat PDF, which you can do using the **Knit** button.

* Unlike **Knit**, **Preview** does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed. So, when you use **Preview**, please make sure that you have once run all the chunks of code in the editor. Once you run all chunks and then preview, the resulting html output will show all code and all output (plots, tables, etc).

* This notebook contains all code, output and answers, for all of the 7 Questions (and all its sub-parts). By that I mean, it also contain answers to theory questions (ones in which I am asked about my observations and insights, e.g. Q7:part-3).

* I have also attached a complete pre-knitted PDF (with all code, output, answers) in my submission files (along side this .Rmd file).

* Feel free to reach out to me at **aarshbatra.in@gmail.com**/8800592799 if you have any questions or run into any problems. I will quickly troubleshoot it for you.



## Documentation

Documentation for all helper functions can be found in the **man** sub-directory.

## Data

Raw data files (total number of files: 3) can be found in the **data-raw** sub-directory.

## Have Questions or running into problems?

Feel free to reach out to me at **aarshbatra.in@gmail.com**/8800592799. I will quickly troubleshoot it for you.
